kujaff\VersionsBundle\Entity\BundleVersion:
    type: entity
    table: versions_bundles
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
        installationDate:
            type: datetime
        installedVersion:
            type: version
            length: '10'
        updateDate:
            type: datetime
            nullable: true
            
    lifecycleCallbacks: {  }