services:
    
    bundle.version:
        class: kujaff\VersionsBundle\Versions\Service
        arguments: [@service_container]
        
    bundle.installer:
        class: kujaff\VersionsBundle\Installer\Service
        arguments: [@service_container]
        
    versionsbundle.installer.install:
        class: kujaff\VersionsBundle\Install\Install
        arguments: [ @service_container ]
        tags:
            - { name: bundle.install }

    versionsbundle.installer.update:
        class: kujaff\VersionsBundle\Install\Update
        arguments: [ @service_container ]
        tags:
            - { name: bundle.update }

    versionsbundle.installer.uninstall:
        class: kujaff\VersionsBundle\Install\Uninstall
        arguments: [ @service_container ]
        tags:
            - { name: bundle.uninstall }

    bundle.generator:
        class: kujaff\VersionsBundle\Generator\Bundle
        arguments: [ @service_container ]
    
    bundle.generator.registerService:
        class: kujaff\VersionsBundle\Generator\RegisterService
        arguments: [ @service_container ]