services:
    versions.bundle:
        class: kujaff\VersionsBundle\Service\BundleVersion
        calls:
            - [ setContainer, [ @service_container ] ]
            
    versions.version:
        class: kujaff\VersionsBundle\Service\Version
        calls:
            - [ setContainer, [ @service_container ] ]
        
    versions.installer:
        class: kujaff\VersionsBundle\Service\Installer
        calls:
            - [ setContainer, [ @service_container ] ]

    versions.generator:
        class: kujaff\VersionsBundle\Service\Generator
        calls:
            - [ setContainer, [ @service_container ] ]
        
    versions.install.install:
        class: kujaff\VersionsBundle\Service\Install\Install
        tags:
            - { name: bundle.install }
        calls:
            - [ setContainer, [ @service_container ] ]
            
    versions.install.update:
        class: kujaff\VersionsBundle\Service\Install\Update
        tags:
            - { name: bundle.update }
        calls:
            - [ setContainer, [ @service_container ] ]

    versions.install.uninstall:
        class: kujaff\VersionsBundle\Service\Install\Uninstall
        tags:
            - { name: bundle.uninstall }
        calls:
            - [ setContainer, [ @service_container ] ]