services:
    
    bundle.version:
        class: kujaff\VersionsBundle\Versions\Service
        arguments: [@service_container]
        
    bundle.installer:
        class: kujaff\VersionsBundle\Installer\Service
        arguments: [@service_container]
        
    versionsbundle.install:
        class: kujaff\VersionsBundle\Install\Install
        arguments: [ @service_container ]
        tags:
            - { name: bundle.install }
            - { name: bundle.uninstall }